server {
        listen 80;

        location = /auth {
            internal;
            proxy_pass http://auth-service:8000/auth;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Original-URI $request_uri;
        }

        location = /auth_check {
            proxy_pass http://auth-service:8000/auth_check;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location = /logout {
            proxy_pass http://auth-service:8000/logout;
            proxy_set_header X-Real-IP $remote_addr;
        }

        error_page 401 = /login;

        location /login {
            proxy_pass http://auth-service:8000/login;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Original-URI $request_uri;
        }

        location / {
            auth_request /auth;
            proxy_pass http://backend;
        }
    }
